# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hatano',
                'doc_host': 'https://nakamura196.github.io',
                'git_url': 'https://github.com/nakamura196/hatano',
                'lib_path': 'hatano'},
  'syms': { 'hatano.core': { 'hatano.core.Client': ('core.html#client', 'hatano/core.py'),
                             'hatano.core.Client.__init__': ('core.html#client.__init__', 'hatano/core.py'),
                             'hatano.core.Client.extract_char': ('core.html#client.extract_char', 'hatano/core.py'),
                             'hatano.core.Client.visualize': ('core.html#client.visualize', 'hatano/core.py')}}}
