"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['Client']

# %% ../nbs/00_core.ipynb 3
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import io
from matplotlib import font_manager
import japanize_matplotlib  # 日本語フォントのサポート

# %% ../nbs/00_core.ipynb 4
class Client:
    def __init__(self, path):
        self.sheets = pd.read_excel(path, sheet_name=None)
        self.term = None

    def extract_char(self, term):
        self.term = term
        sheets = self.sheets
        rows_target = []

        for sheet_name, df in sheets.items():
            column_names = df.columns.tolist()
            if column_names[0] != "ID":
                continue

            for i, row in df.iterrows():
                char = row["Char"]
                # print(char)
                if char != term:
                    continue
                rows_target.append(row)

        return pd.DataFrame(rows_target)

    def visualize(self, df):
        # Create figure
        fig, ax = plt.subplots()
        
        # 散布図を作成
        ax.scatter(df['beside'], df['Angle'])
        
        # 軸の範囲を設定
        ax.set_xlim(0, 2)
        ax.set_ylim(0, 30)
        
        # タイトルと軸ラベルを設定
        ax.set_title(f'"{self.term}"の比較')
        ax.set_xlabel('縦横比')
        ax.set_ylabel('傾き')
        
        return fig

